version: "3.4"

services:
  web:
    image: mysql
    hostname: mysqldb
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysqldata:/var/lib/mysql
      - ./misc:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  mysqldata:
